name: CI

# on: 
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main


on:
  workflow_dispatch:
    inputs:
      namespace:
        description: 'this is of eks hpa task'
        required: true
        default: 'default'
        type: string
      node-min-size:
        description: 'min size of node'
        required: true
        default: '1' 
        type: string
      node-max-size:
        description: 'max size of node'
        required: true
        default: '10' 
        type: string
      hpa-min-size:
        description: 'hpa min size'
        required: true
        default: '2'
        type: string
      hpa-max-size:
        description: 'hpa max size'
        required: true
        default: '10'
        type: string
        
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Run tests
      run: |
        python -m unittest discover

    - name: my-step
      run: echo "Hello World!" 
